/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadIndexRouteImport } from './routes/upload/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as GalleryBlobIdIndexRouteImport } from './routes/gallery/$blobId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadIndexRoute = UploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryBlobIdIndexRoute = GalleryBlobIdIndexRouteImport.update({
  id: '/gallery/$blobId/',
  path: '/gallery/$blobId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/upload/': typeof UploadIndexRoute
  '/gallery/$blobId/': typeof GalleryBlobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin': typeof AdminIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/upload': typeof UploadIndexRoute
  '/gallery/$blobId': typeof GalleryBlobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/upload/': typeof UploadIndexRoute
  '/gallery/$blobId/': typeof GalleryBlobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/gallery/'
    | '/upload/'
    | '/gallery/$blobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin'
    | '/gallery'
    | '/upload'
    | '/gallery/$blobId'
  id:
    | '__root__'
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/gallery/'
    | '/upload/'
    | '/gallery/$blobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  UploadIndexRoute: typeof UploadIndexRoute
  GalleryBlobIdIndexRoute: typeof GalleryBlobIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/': {
      id: '/upload/'
      path: '/upload'
      fullPath: '/upload/'
      preLoaderRoute: typeof UploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$blobId/': {
      id: '/gallery/$blobId/'
      path: '/gallery/$blobId'
      fullPath: '/gallery/$blobId/'
      preLoaderRoute: typeof GalleryBlobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  UploadIndexRoute: UploadIndexRoute,
  GalleryBlobIdIndexRoute: GalleryBlobIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
